# Generated by Django 5.2.15 on 2026-06-09 12:40

import breakfast.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(default=breakfast.models.gen_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('arabic', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_fee', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.CharField(default=breakfast.models.gen_id, max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('arabic', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('kind', models.CharField(default='plate', max_length=16)),
                ('available', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='breakfast.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=breakfast.models.gen_id, max_length=64, primary_key=True, serialize=False)),
                ('started_by', models.CharField(max_length=80)),
                ('status', models.CharField(default='open', max_length=16)),
                ('service_date', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='breakfast.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=breakfast.models.gen_id, max_length=64, primary_key=True, serialize=False)),
                ('person', models.CharField(max_length=80)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='breakfast.session')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.CharField(default=breakfast.models.gen_id, max_length=64, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('for_name', models.CharField(blank=True, max_length=80, null=True)),
                ('unit_price', models.IntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='breakfast.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='breakfast.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='breakfast_o_order_i_735e11_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant'], name='breakfast_m_restaur_59ea44_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['restaurant', 'status'], name='breakfast_s_restaur_851fb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('restaurant', 'service_date'), name='one_open_session_per_restaurant_per_day'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['session'], name='breakfast_o_session_7917c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('session', 'person'), name='one_order_per_person'),
        ),
    ]
