# Generated by Django 5.2.15 on 2026-06-10 10:26

from django.db import migrations, models


def backfill_from_restaurant(apps, schema_editor):
    Session = apps.get_model('breakfast', 'Session')
    for s in Session.objects.select_related('restaurant').filter(delivery_fee__isnull=True):
        s.delivery_fee = s.restaurant.delivery_fee
        s.save(update_fields=['delivery_fee'])


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='delivery_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_from_restaurant, migrations.RunPython.noop),
    ]
