# Generated by Django 5.2.15 on 2026-06-10 13:46

from django.db import migrations, models

# "Users" for the admin: people exist only as names on orders, so aggregate
# them in a view. One row per person; money in piasters.
CREATE_VIEW = """
CREATE VIEW breakfast_person_stats AS
SELECT
    o.person                                                          AS name,
    COUNT(DISTINCT o.id)                                              AS orders_count,
    COUNT(DISTINCT o.session_id)                                      AS mornings,
    COUNT(DISTINCT o.id) FILTER (WHERE s.status = 'closed' AND NOT o.paid) AS unpaid_count,
    COALESCE(SUM(l.qty * l.unit_price), 0)::bigint                    AS items_total,
    MAX(o.created_at)                                                 AS last_seen
FROM breakfast_order o
JOIN breakfast_session s ON s.id = o.session_id
LEFT JOIN breakfast_orderline l ON l.order_id = o.id
GROUP BY o.person;
"""

DROP_VIEW = 'DROP VIEW IF EXISTS breakfast_person_stats;'


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0002_session_delivery_fee'),
    ]

    operations = [
        migrations.RunSQL(CREATE_VIEW, DROP_VIEW),
        migrations.CreateModel(
            name='PersonStats',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('orders_count', models.IntegerField()),
                ('mornings', models.IntegerField()),
                ('unpaid_count', models.IntegerField()),
                ('items_total', models.BigIntegerField()),
                ('last_seen', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'db_table': 'breakfast_person_stats',
                'managed': False,
            },
        ),
    ]
