# Generated by Django 5.2.15 on 2026-06-10 15:19

import breakfast.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0003_personstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.CharField(default=breakfast.models.gen_id, editable=False, max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=breakfast.models.gen_id, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='id',
            field=models.CharField(default=breakfast.models.gen_id, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.CharField(default=breakfast.models.gen_id, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=breakfast.models.gen_id, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
